---
- name: tomcat install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        - name: openjdk-11-jdk
          update_cache: yes
          state: yes
      