---
- name: tomcat install on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: java install
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present    
    - name: create  tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download tomcat 10.1.4 
      ansible.builtin.get_url:
        url: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz
        dest: /tmp/apache-tomcat-10.1.4.tar.gz
    - name: extract tomcat
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz
        remote_src: yes
        dest: /opt/tomcat
    - name: symbolic link tomcat
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.4
        dest: /opt/tomcat/latest
        state: link
    - name: change permission 
      ansible.builtin.file:
        dest: /opt/tomcat
        recurse: true
        owner: tomcat
        group: tomcat
        state: directory
    - name: add execute permissions to shell files
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: create a systemd unit
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload daemon, start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: true
        enabled: yes
        state: started
    - name: copy the user xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat
    - name: copy the  manger app contex xml
      ansible.builtin.copy:
        src: contex.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: copy the host  manger app contex xml
      ansible.builtin.copy:
        src: hostmanger-contex.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat    
    - name: tomcat restart
      ansible.builtin.systemd:
        name: tomcat.service
        state: resarted
            


          

